name: PMD Scan

on: [push, pull_request]

jobs:
  pmd:
    name: Run PMD Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Use the appropriate Java version
          distribution: 'temurin'
      - name: Download and unzip PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.41.0/pmd-bin-6.41.0.zip
          unzip pmd-bin-6.41.0.zip
        working-directory: ${{ github.workspace }}

      - name: Run PMD
        run: |
          ./pmd-bin-6.41.0/bin/run.sh pmd -d ./src -f text -R pmd.xml
        working-directory: ${{ github.workspace }}
